#!/usr/bin/env bash

# Get the currently staged files
declare -a STAGED_FILES=($(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g'))

# Quit if nothing is staged
[ -z "$STAGED_FILES" ] && exit 0

# Determine the package runner via lock files, falling back to "npx"
# yarn outputs extra text on running packages, so need to silence that with --silent option
[ -z "$PACKAGE_RUNNER" ] && [ -f "./yarn.lock" ] && PACKAGE_RUNNER="yarn --silent"
[ -z "$PACKAGE_RUNNER" ] && [ -f "./pnpm-lock.yaml" ] && PACKAGE_RUNNER="pnpm"
[ -z "$PACKAGE_RUNNER" ] && [ -f "./package-lock.json" ] && PACKAGE_RUNNER="npx"
[ -z "$PACKAGE_RUNNER" ] && PACKAGE_RUNNER="npx"

ESLINT_INSTALLED=$(npm --silent list eslint >/dev/null && echo true || echo false)

# Lint staged files with eslint if it is installed in the project
if [ "$ESLINT_INSTALLED" = "true" ]; then
  # Filter the staged files by file extension that we want to lint
  STAGED_FILES_TO_LINT=$((IFS=$'\n' && echo "${STAGED_FILES[*]}") | grep -E '.*\.(js|jsx|tsx|ts)$')

  # Get files that eslint can process, which will not throw "Ignored" warnings
  LINTABLE_FILES=$($PACKAGE_RUNNER esif ${STAGED_FILES_TO_LINT})

  # Exit if no staged files are lintable
  [ -z "$LINTABLE_FILES" ] && exit 0

  echo ""
  echo Running eslint on staged files...
  # Run eslint using the detected package runner
  $PACKAGE_RUNNER eslint $LINTABLE_FILES --max-warnings 0 --report-unused-disable-directives #--fix

  # Get the eslint exit code
  ESLINT_EXIT="$?"

  # Re-add files since they may have been fixed
  # Remove the next line if you are not running eslint with the --fix option
  # git add "${LINTABLE_FILES}"

  # Test the eslint exit code for non-zero status
  if [[ "${ESLINT_EXIT}" == 0 ]]; then
    printf "\033[32m✔\033[0m Ok\n"
  else
    printf "\n\033[31mCOMMIT FAILED:\033[0m Fix eslint errors and try again"
    exit $ESLINT_EXIT
  fi
fi


# Prettify all selected files
if [ -f "./node_modules/.bin/prettier" ]; then
echo ""
echo Running prettier on staged files...
  $PACKAGE_RUNNER prettier $STAGED_FILES_TO_LINT --ignore-unknown --write --loglevel warn
  PRETTIER_EXIT="$?"

  if [[ "${PRETTIER_EXIT}" == 0 ]]; then
    printf "\033[32m✔\033[0m Ok\n"
  else
    printf "\n\033[31mCOMMIT FAILED:\033[0m Fix prettier errors and try again\n"
    exit $PRETTIER_EXIT
  fi

  # Add back the modified/prettified files to staging
  echo "$STAGED_FILES_TO_LINT" | xargs git add
fi

exit 0
