version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    commit-message:
      prefix: 'chore'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/'
    commit-message:
      prefix: 'chore'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: 'prettier'
        update-types: ['version-update:semver-major'] # ignore major updates until @nrwl/nx adds support for prettier v3
      - dependency-name: '@storybook/*' # ignore storybook updates (should be managed by `npx storybook@latest upgrade`)
      - dependency-name: 'storybook' # ignore storybook updates (should be managed by `npx storybook@latest upgrade`)
      - dependency-name: '@nx/*' # ignore nx updates (should be managed by `npx nx migrate latest`)
      - dependency-name: 'nx' # ignore nx updates (should be managed by `npx nx migrate latest`)
    groups:
      production-dependencies:
        dependency-type: 'production'
      develepmont-dependencies:
        dependency-type: 'development'

      # * Example patterns if you want to group by package name / scope *
      # eslint:
      #   patterns:
      #     - 'eslint'
      #     - '@eslint/*'
      #     - 'eslint-plugin-*'
      #     - '@typescript-eslint/*'
      # vite:
      #   patterns:
      #     - 'vite'
      #     - '@vitejs/*'
      #     - 'vite-plugin-*'
      #     - 'vitest'
      #     - '@vitest/*'