version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    commit-message:
      prefix: 'chore'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/'
    commit-message:
      prefix: 'chore'
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: 'prettier'
        update-types: ['version-update:semver-major']
      - dependency-name: '@storybook/*'
      - dependency-name: 'storybook'
      - dependency-name: '@nx/*'
      - dependency-name: 'nx'
    groups:
      nx:
        patterns:
          - 'nx'
          - '@nx/*'
      commitlint:
        patterns:
          - '@commitlint/*'
      storybook:
        patterns:
          - 'storybook'
          - '@storybook/*'
      eslint:
        patterns:
          - 'eslint'
          - '@eslint/*'
          - 'eslint-plugin-*'
          - '@typescript-eslint/*'
      swc:
        patterns:
          - 'swc'
          - '@swc/*'
      types:
        patterns:
          - '@types/*'
      vite:
        patterns:
          - 'vite'
          - '@vitejs/*'
          - 'vite-plugin-*'
          - 'vitest'
          - '@vitest/*'
      radix:
        patterns:
          - '@radix-ui/*'
